### ISSUE TITLE
Illegal reflective access: SunGraphics2D

### ISSUE THREAD

**Issue by defndaines** [defndaines/meiro#57]
Using a more recent version of the JDK (14) and Clojure (1.10.1), I get the following when trying to render a PNG at the REPL:
```
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000800d00440 (file:.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar) to method sun.java2d.SunGraphics2D.draw(java.awt.Shape)
```

Note, I stumbled on this first with the open JDK, but then installed the Oracle version to see if it was a permission issue there, but it happens in both.

**Comment by defndaines** [comment]
Fixed with 207580732e7681de7f53d31180f9b6c7cdb80535

With JDK 13 and 14, functions for rendering 3D mazes were failing because they didn't have type hints. Adding in the type hints solves the problem.

Note, I added the following (temporarily) to the profile.clj in order to debug:
```
  :jvm-opts ["--illegal-access=debug"]
```

It provided stacktraces like this:
```
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000800b8c840 (file:.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar) to method sun.java2d.SunGraphics2D.draw(java.awt.Shape)
        at clojure.lang.Reflector.canAccess(Reflector.java:49)
        at clojure.lang.Reflector.toAccessibleSuperMethod(Reflector.java:84)
        at clojure.lang.Reflector.lambda$invokeInstanceMethod$0(Reflector.java:99)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:101)
        at meiro.png$draw_up_arrow.invokeStatic(png.clj:356)
        at meiro.png$draw_up_arrow.invoke(png.clj:349)
        at meiro.png$render_3d.invokeStatic(png.clj:415)
        at meiro.png$render_3d.invoke(png.clj:383)
```
